/* soapH.h
   Generated by gSOAP 2.7.9l from onvif.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_ns2__FaultSubcodeValues
#define SOAP_TYPE_ns2__FaultSubcodeValues (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__FaultSubcodeValues(struct soap*, enum ns2__FaultSubcodeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__FaultSubcodeValues(struct soap*, const enum ns2__FaultSubcodeValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__FaultSubcodeValues(struct soap*, const char*, int, const enum ns2__FaultSubcodeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__FaultSubcodeValues2s(struct soap*, enum ns2__FaultSubcodeValues);
SOAP_FMAC3 enum ns2__FaultSubcodeValues * SOAP_FMAC4 soap_get_ns2__FaultSubcodeValues(struct soap*, enum ns2__FaultSubcodeValues *, const char*, const char*);
SOAP_FMAC3 enum ns2__FaultSubcodeValues * SOAP_FMAC4 soap_in_ns2__FaultSubcodeValues(struct soap*, const char*, enum ns2__FaultSubcodeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__FaultSubcodeValues(struct soap*, const char*, enum ns2__FaultSubcodeValues *);

#ifndef SOAP_TYPE_ns2__RelationshipTypeValues
#define SOAP_TYPE_ns2__RelationshipTypeValues (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__RelationshipTypeValues(struct soap*, enum ns2__RelationshipTypeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__RelationshipTypeValues(struct soap*, const enum ns2__RelationshipTypeValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__RelationshipTypeValues(struct soap*, const char*, int, const enum ns2__RelationshipTypeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__RelationshipTypeValues2s(struct soap*, enum ns2__RelationshipTypeValues);
SOAP_FMAC3 enum ns2__RelationshipTypeValues * SOAP_FMAC4 soap_get_ns2__RelationshipTypeValues(struct soap*, enum ns2__RelationshipTypeValues *, const char*, const char*);
SOAP_FMAC3 enum ns2__RelationshipTypeValues * SOAP_FMAC4 soap_in_ns2__RelationshipTypeValues(struct soap*, const char*, enum ns2__RelationshipTypeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__RelationshipTypeValues(struct soap*, const char*, enum ns2__RelationshipTypeValues *);

#ifndef SOAP_TYPE_ns1__FaultCodeType
#define SOAP_TYPE_ns1__FaultCodeType (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__FaultCodeType(struct soap*, enum ns1__FaultCodeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__FaultCodeType(struct soap*, const enum ns1__FaultCodeType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__FaultCodeType(struct soap*, const char*, int, const enum ns1__FaultCodeType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns1__FaultCodeType2s(struct soap*, enum ns1__FaultCodeType);
SOAP_FMAC3 enum ns1__FaultCodeType * SOAP_FMAC4 soap_get_ns1__FaultCodeType(struct soap*, enum ns1__FaultCodeType *, const char*, const char*);
SOAP_FMAC3 enum ns1__FaultCodeType * SOAP_FMAC4 soap_in_ns1__FaultCodeType(struct soap*, const char*, enum ns1__FaultCodeType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns1__FaultCodeType(struct soap*, const char*, enum ns1__FaultCodeType *);

#ifndef SOAP_TYPE_ns1__RelationshipType
#define SOAP_TYPE_ns1__RelationshipType (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RelationshipType(struct soap*, enum ns1__RelationshipType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RelationshipType(struct soap*, const enum ns1__RelationshipType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RelationshipType(struct soap*, const char*, int, const enum ns1__RelationshipType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns1__RelationshipType2s(struct soap*, enum ns1__RelationshipType);
SOAP_FMAC3 enum ns1__RelationshipType * SOAP_FMAC4 soap_get_ns1__RelationshipType(struct soap*, enum ns1__RelationshipType *, const char*, const char*);
SOAP_FMAC3 enum ns1__RelationshipType * SOAP_FMAC4 soap_in_ns1__RelationshipType(struct soap*, const char*, enum ns1__RelationshipType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns1__RelationshipType(struct soap*, const char*, enum ns1__RelationshipType *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns4__Probe
#define SOAP_TYPE___ns4__Probe (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__Probe(struct soap*, struct __ns4__Probe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__Probe(struct soap*, const struct __ns4__Probe *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__Probe(struct soap*, const struct __ns4__Probe *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__Probe(struct soap*, const char*, int, const struct __ns4__Probe *, const char*);
SOAP_FMAC3 struct __ns4__Probe * SOAP_FMAC4 soap_get___ns4__Probe(struct soap*, struct __ns4__Probe *, const char*, const char*);
SOAP_FMAC3 struct __ns4__Probe * SOAP_FMAC4 soap_in___ns4__Probe(struct soap*, const char*, struct __ns4__Probe *, const char*);

#ifndef SOAP_TYPE___ns3__Bye
#define SOAP_TYPE___ns3__Bye (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__Bye(struct soap*, struct __ns3__Bye *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__Bye(struct soap*, const struct __ns3__Bye *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__Bye(struct soap*, const struct __ns3__Bye *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__Bye(struct soap*, const char*, int, const struct __ns3__Bye *, const char*);
SOAP_FMAC3 struct __ns3__Bye * SOAP_FMAC4 soap_get___ns3__Bye(struct soap*, struct __ns3__Bye *, const char*, const char*);
SOAP_FMAC3 struct __ns3__Bye * SOAP_FMAC4 soap_in___ns3__Bye(struct soap*, const char*, struct __ns3__Bye *, const char*);

#ifndef SOAP_TYPE___ns3__Hello
#define SOAP_TYPE___ns3__Hello (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__Hello(struct soap*, struct __ns3__Hello *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__Hello(struct soap*, const struct __ns3__Hello *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__Hello(struct soap*, const struct __ns3__Hello *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__Hello(struct soap*, const char*, int, const struct __ns3__Hello *, const char*);
SOAP_FMAC3 struct __ns3__Hello * SOAP_FMAC4 soap_get___ns3__Hello(struct soap*, struct __ns3__Hello *, const char*, const char*);
SOAP_FMAC3 struct __ns3__Hello * SOAP_FMAC4 soap_in___ns3__Hello(struct soap*, const char*, struct __ns3__Hello *, const char*);

#ifndef SOAP_TYPE_ns2__RetryAfterType
#define SOAP_TYPE_ns2__RetryAfterType (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__RetryAfterType(struct soap*, struct ns2__RetryAfterType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__RetryAfterType(struct soap*, const struct ns2__RetryAfterType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__RetryAfterType(struct soap*, const struct ns2__RetryAfterType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__RetryAfterType(struct soap*, const char*, int, const struct ns2__RetryAfterType *, const char*);
SOAP_FMAC3 struct ns2__RetryAfterType * SOAP_FMAC4 soap_get_ns2__RetryAfterType(struct soap*, struct ns2__RetryAfterType *, const char*, const char*);
SOAP_FMAC3 struct ns2__RetryAfterType * SOAP_FMAC4 soap_in_ns2__RetryAfterType(struct soap*, const char*, struct ns2__RetryAfterType *, const char*);

#ifndef SOAP_TYPE_ns2__ReplyAfterType
#define SOAP_TYPE_ns2__ReplyAfterType (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ReplyAfterType(struct soap*, struct ns2__ReplyAfterType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ReplyAfterType(struct soap*, const struct ns2__ReplyAfterType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ReplyAfterType(struct soap*, const struct ns2__ReplyAfterType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ReplyAfterType(struct soap*, const char*, int, const struct ns2__ReplyAfterType *, const char*);
SOAP_FMAC3 struct ns2__ReplyAfterType * SOAP_FMAC4 soap_get_ns2__ReplyAfterType(struct soap*, struct ns2__ReplyAfterType *, const char*, const char*);
SOAP_FMAC3 struct ns2__ReplyAfterType * SOAP_FMAC4 soap_in_ns2__ReplyAfterType(struct soap*, const char*, struct ns2__ReplyAfterType *, const char*);

#ifndef SOAP_TYPE_ns2__Relationship
#define SOAP_TYPE_ns2__Relationship (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Relationship(struct soap*, struct ns2__Relationship *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Relationship(struct soap*, const struct ns2__Relationship *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Relationship(struct soap*, const struct ns2__Relationship *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Relationship(struct soap*, const char*, int, const struct ns2__Relationship *, const char*);
SOAP_FMAC3 struct ns2__Relationship * SOAP_FMAC4 soap_get_ns2__Relationship(struct soap*, struct ns2__Relationship *, const char*, const char*);
SOAP_FMAC3 struct ns2__Relationship * SOAP_FMAC4 soap_in_ns2__Relationship(struct soap*, const char*, struct ns2__Relationship *, const char*);

#ifndef SOAP_TYPE_ns1__AppSequenceType
#define SOAP_TYPE_ns1__AppSequenceType (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__AppSequenceType(struct soap*, struct ns1__AppSequenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__AppSequenceType(struct soap*, const struct ns1__AppSequenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__AppSequenceType(struct soap*, const struct ns1__AppSequenceType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AppSequenceType(struct soap*, const char*, int, const struct ns1__AppSequenceType *, const char*);
SOAP_FMAC3 struct ns1__AppSequenceType * SOAP_FMAC4 soap_get_ns1__AppSequenceType(struct soap*, struct ns1__AppSequenceType *, const char*, const char*);
SOAP_FMAC3 struct ns1__AppSequenceType * SOAP_FMAC4 soap_in_ns1__AppSequenceType(struct soap*, const char*, struct ns1__AppSequenceType *, const char*);

#ifndef SOAP_TYPE_ns2__ServiceNameType
#define SOAP_TYPE_ns2__ServiceNameType (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ServiceNameType(struct soap*, struct ns2__ServiceNameType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ServiceNameType(struct soap*, const struct ns2__ServiceNameType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ServiceNameType(struct soap*, const struct ns2__ServiceNameType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ServiceNameType(struct soap*, const char*, int, const struct ns2__ServiceNameType *, const char*);
SOAP_FMAC3 struct ns2__ServiceNameType * SOAP_FMAC4 soap_get_ns2__ServiceNameType(struct soap*, struct ns2__ServiceNameType *, const char*, const char*);
SOAP_FMAC3 struct ns2__ServiceNameType * SOAP_FMAC4 soap_in_ns2__ServiceNameType(struct soap*, const char*, struct ns2__ServiceNameType *, const char*);

#ifndef SOAP_TYPE_ns2__AttributedQName
#define SOAP_TYPE_ns2__AttributedQName (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__AttributedQName(struct soap*, struct ns2__AttributedQName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__AttributedQName(struct soap*, const struct ns2__AttributedQName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__AttributedQName(struct soap*, const struct ns2__AttributedQName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__AttributedQName(struct soap*, const char*, int, const struct ns2__AttributedQName *, const char*);
SOAP_FMAC3 struct ns2__AttributedQName * SOAP_FMAC4 soap_get_ns2__AttributedQName(struct soap*, struct ns2__AttributedQName *, const char*, const char*);
SOAP_FMAC3 struct ns2__AttributedQName * SOAP_FMAC4 soap_in_ns2__AttributedQName(struct soap*, const char*, struct ns2__AttributedQName *, const char*);

#ifndef SOAP_TYPE_ns2__ReferenceParametersType
#define SOAP_TYPE_ns2__ReferenceParametersType (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ReferenceParametersType(struct soap*, struct ns2__ReferenceParametersType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ReferenceParametersType(struct soap*, const struct ns2__ReferenceParametersType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ReferenceParametersType(struct soap*, const struct ns2__ReferenceParametersType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ReferenceParametersType(struct soap*, const char*, int, const struct ns2__ReferenceParametersType *, const char*);
SOAP_FMAC3 struct ns2__ReferenceParametersType * SOAP_FMAC4 soap_get_ns2__ReferenceParametersType(struct soap*, struct ns2__ReferenceParametersType *, const char*, const char*);
SOAP_FMAC3 struct ns2__ReferenceParametersType * SOAP_FMAC4 soap_in_ns2__ReferenceParametersType(struct soap*, const char*, struct ns2__ReferenceParametersType *, const char*);

#ifndef SOAP_TYPE_ns2__ReferencePropertiesType
#define SOAP_TYPE_ns2__ReferencePropertiesType (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ReferencePropertiesType(struct soap*, struct ns2__ReferencePropertiesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ReferencePropertiesType(struct soap*, const struct ns2__ReferencePropertiesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ReferencePropertiesType(struct soap*, const struct ns2__ReferencePropertiesType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ReferencePropertiesType(struct soap*, const char*, int, const struct ns2__ReferencePropertiesType *, const char*);
SOAP_FMAC3 struct ns2__ReferencePropertiesType * SOAP_FMAC4 soap_get_ns2__ReferencePropertiesType(struct soap*, struct ns2__ReferencePropertiesType *, const char*, const char*);
SOAP_FMAC3 struct ns2__ReferencePropertiesType * SOAP_FMAC4 soap_in_ns2__ReferencePropertiesType(struct soap*, const char*, struct ns2__ReferencePropertiesType *, const char*);

#ifndef SOAP_TYPE_ns2__AttributedURI
#define SOAP_TYPE_ns2__AttributedURI (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__AttributedURI(struct soap*, struct ns2__AttributedURI *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__AttributedURI(struct soap*, const struct ns2__AttributedURI *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__AttributedURI(struct soap*, const struct ns2__AttributedURI *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__AttributedURI(struct soap*, const char*, int, const struct ns2__AttributedURI *, const char*);
SOAP_FMAC3 struct ns2__AttributedURI * SOAP_FMAC4 soap_get_ns2__AttributedURI(struct soap*, struct ns2__AttributedURI *, const char*, const char*);
SOAP_FMAC3 struct ns2__AttributedURI * SOAP_FMAC4 soap_in_ns2__AttributedURI(struct soap*, const char*, struct ns2__AttributedURI *, const char*);

#ifndef SOAP_TYPE_ns1__SigType
#define SOAP_TYPE_ns1__SigType (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SigType(struct soap*, struct ns1__SigType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SigType(struct soap*, const struct ns1__SigType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SigType(struct soap*, const struct ns1__SigType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SigType(struct soap*, const char*, int, const struct ns1__SigType *, const char*);
SOAP_FMAC3 struct ns1__SigType * SOAP_FMAC4 soap_get_ns1__SigType(struct soap*, struct ns1__SigType *, const char*, const char*);
SOAP_FMAC3 struct ns1__SigType * SOAP_FMAC4 soap_in_ns1__SigType(struct soap*, const char*, struct ns1__SigType *, const char*);

#ifndef SOAP_TYPE_ns1__SecurityType
#define SOAP_TYPE_ns1__SecurityType (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SecurityType(struct soap*, struct ns1__SecurityType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SecurityType(struct soap*, const struct ns1__SecurityType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SecurityType(struct soap*, const struct ns1__SecurityType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SecurityType(struct soap*, const char*, int, const struct ns1__SecurityType *, const char*);
SOAP_FMAC3 struct ns1__SecurityType * SOAP_FMAC4 soap_get_ns1__SecurityType(struct soap*, struct ns1__SecurityType *, const char*, const char*);
SOAP_FMAC3 struct ns1__SecurityType * SOAP_FMAC4 soap_in_ns1__SecurityType(struct soap*, const char*, struct ns1__SecurityType *, const char*);

#ifndef SOAP_TYPE_ns1__ResolveMatchType
#define SOAP_TYPE_ns1__ResolveMatchType (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ResolveMatchType(struct soap*, struct ns1__ResolveMatchType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ResolveMatchType(struct soap*, const struct ns1__ResolveMatchType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ResolveMatchType(struct soap*, const struct ns1__ResolveMatchType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ResolveMatchType(struct soap*, const char*, int, const struct ns1__ResolveMatchType *, const char*);
SOAP_FMAC3 struct ns1__ResolveMatchType * SOAP_FMAC4 soap_get_ns1__ResolveMatchType(struct soap*, struct ns1__ResolveMatchType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ResolveMatchType * SOAP_FMAC4 soap_in_ns1__ResolveMatchType(struct soap*, const char*, struct ns1__ResolveMatchType *, const char*);

#ifndef SOAP_TYPE_ns1__ResolveMatchesType
#define SOAP_TYPE_ns1__ResolveMatchesType (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ResolveMatchesType(struct soap*, struct ns1__ResolveMatchesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ResolveMatchesType(struct soap*, const struct ns1__ResolveMatchesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ResolveMatchesType(struct soap*, const struct ns1__ResolveMatchesType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ResolveMatchesType(struct soap*, const char*, int, const struct ns1__ResolveMatchesType *, const char*);
SOAP_FMAC3 struct ns1__ResolveMatchesType * SOAP_FMAC4 soap_get_ns1__ResolveMatchesType(struct soap*, struct ns1__ResolveMatchesType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ResolveMatchesType * SOAP_FMAC4 soap_in_ns1__ResolveMatchesType(struct soap*, const char*, struct ns1__ResolveMatchesType *, const char*);

#ifndef SOAP_TYPE_ns1__ResolveType
#define SOAP_TYPE_ns1__ResolveType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ResolveType(struct soap*, struct ns1__ResolveType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ResolveType(struct soap*, const struct ns1__ResolveType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ResolveType(struct soap*, const struct ns1__ResolveType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ResolveType(struct soap*, const char*, int, const struct ns1__ResolveType *, const char*);
SOAP_FMAC3 struct ns1__ResolveType * SOAP_FMAC4 soap_get_ns1__ResolveType(struct soap*, struct ns1__ResolveType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ResolveType * SOAP_FMAC4 soap_in_ns1__ResolveType(struct soap*, const char*, struct ns1__ResolveType *, const char*);

#ifndef SOAP_TYPE_ns1__ProbeMatchType
#define SOAP_TYPE_ns1__ProbeMatchType (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ProbeMatchType(struct soap*, struct ns1__ProbeMatchType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ProbeMatchType(struct soap*, const struct ns1__ProbeMatchType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ProbeMatchType(struct soap*, const struct ns1__ProbeMatchType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProbeMatchType(struct soap*, const char*, int, const struct ns1__ProbeMatchType *, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchType * SOAP_FMAC4 soap_get_ns1__ProbeMatchType(struct soap*, struct ns1__ProbeMatchType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchType * SOAP_FMAC4 soap_in_ns1__ProbeMatchType(struct soap*, const char*, struct ns1__ProbeMatchType *, const char*);

#ifndef SOAP_TYPE_ns1__ProbeMatchesType
#define SOAP_TYPE_ns1__ProbeMatchesType (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ProbeMatchesType(struct soap*, struct ns1__ProbeMatchesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ProbeMatchesType(struct soap*, const struct ns1__ProbeMatchesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ProbeMatchesType(struct soap*, const struct ns1__ProbeMatchesType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProbeMatchesType(struct soap*, const char*, int, const struct ns1__ProbeMatchesType *, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchesType * SOAP_FMAC4 soap_get_ns1__ProbeMatchesType(struct soap*, struct ns1__ProbeMatchesType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchesType * SOAP_FMAC4 soap_in_ns1__ProbeMatchesType(struct soap*, const char*, struct ns1__ProbeMatchesType *, const char*);

#ifndef SOAP_TYPE_ns1__ProbeType
#define SOAP_TYPE_ns1__ProbeType (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ProbeType(struct soap*, struct ns1__ProbeType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ProbeType(struct soap*, const struct ns1__ProbeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ProbeType(struct soap*, const struct ns1__ProbeType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProbeType(struct soap*, const char*, int, const struct ns1__ProbeType *, const char*);
SOAP_FMAC3 struct ns1__ProbeType * SOAP_FMAC4 soap_get_ns1__ProbeType(struct soap*, struct ns1__ProbeType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeType * SOAP_FMAC4 soap_in_ns1__ProbeType(struct soap*, const char*, struct ns1__ProbeType *, const char*);

#ifndef SOAP_TYPE_ns1__ByeType
#define SOAP_TYPE_ns1__ByeType (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ByeType(struct soap*, struct ns1__ByeType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ByeType(struct soap*, const struct ns1__ByeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ByeType(struct soap*, const struct ns1__ByeType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ByeType(struct soap*, const char*, int, const struct ns1__ByeType *, const char*);
SOAP_FMAC3 struct ns1__ByeType * SOAP_FMAC4 soap_get_ns1__ByeType(struct soap*, struct ns1__ByeType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ByeType * SOAP_FMAC4 soap_in_ns1__ByeType(struct soap*, const char*, struct ns1__ByeType *, const char*);

#ifndef SOAP_TYPE_ns1__ScopesType
#define SOAP_TYPE_ns1__ScopesType (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ScopesType(struct soap*, struct ns1__ScopesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ScopesType(struct soap*, const struct ns1__ScopesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ScopesType(struct soap*, const struct ns1__ScopesType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ScopesType(struct soap*, const char*, int, const struct ns1__ScopesType *, const char*);
SOAP_FMAC3 struct ns1__ScopesType * SOAP_FMAC4 soap_get_ns1__ScopesType(struct soap*, struct ns1__ScopesType *, const char*, const char*);
SOAP_FMAC3 struct ns1__ScopesType * SOAP_FMAC4 soap_in_ns1__ScopesType(struct soap*, const char*, struct ns1__ScopesType *, const char*);

#ifndef SOAP_TYPE_ns2__EndpointReferenceType
#define SOAP_TYPE_ns2__EndpointReferenceType (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__EndpointReferenceType(struct soap*, struct ns2__EndpointReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__EndpointReferenceType(struct soap*, const struct ns2__EndpointReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__EndpointReferenceType(struct soap*, const struct ns2__EndpointReferenceType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__EndpointReferenceType(struct soap*, const char*, int, const struct ns2__EndpointReferenceType *, const char*);
SOAP_FMAC3 struct ns2__EndpointReferenceType * SOAP_FMAC4 soap_get_ns2__EndpointReferenceType(struct soap*, struct ns2__EndpointReferenceType *, const char*, const char*);
SOAP_FMAC3 struct ns2__EndpointReferenceType * SOAP_FMAC4 soap_in_ns2__EndpointReferenceType(struct soap*, const char*, struct ns2__EndpointReferenceType *, const char*);

#ifndef SOAP_TYPE_ns1__HelloType
#define SOAP_TYPE_ns1__HelloType (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__HelloType(struct soap*, struct ns1__HelloType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__HelloType(struct soap*, const struct ns1__HelloType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__HelloType(struct soap*, const struct ns1__HelloType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__HelloType(struct soap*, const char*, int, const struct ns1__HelloType *, const char*);
SOAP_FMAC3 struct ns1__HelloType * SOAP_FMAC4 soap_get_ns1__HelloType(struct soap*, struct ns1__HelloType *, const char*, const char*);
SOAP_FMAC3 struct ns1__HelloType * SOAP_FMAC4 soap_in_ns1__HelloType(struct soap*, const char*, struct ns1__HelloType *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__ProbeMatchesType
#define SOAP_TYPE_PointerTons1__ProbeMatchesType (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProbeMatchesType(struct soap*, struct ns1__ProbeMatchesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProbeMatchesType(struct soap*, struct ns1__ProbeMatchesType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProbeMatchesType(struct soap*, const char *, int, struct ns1__ProbeMatchesType *const*, const char *);
SOAP_FMAC3 struct ns1__ProbeMatchesType ** SOAP_FMAC4 soap_get_PointerTons1__ProbeMatchesType(struct soap*, struct ns1__ProbeMatchesType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchesType ** SOAP_FMAC4 soap_in_PointerTons1__ProbeMatchesType(struct soap*, const char*, struct ns1__ProbeMatchesType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ProbeType
#define SOAP_TYPE_PointerTons1__ProbeType (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProbeType(struct soap*, struct ns1__ProbeType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProbeType(struct soap*, struct ns1__ProbeType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProbeType(struct soap*, const char *, int, struct ns1__ProbeType *const*, const char *);
SOAP_FMAC3 struct ns1__ProbeType ** SOAP_FMAC4 soap_get_PointerTons1__ProbeType(struct soap*, struct ns1__ProbeType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeType ** SOAP_FMAC4 soap_in_PointerTons1__ProbeType(struct soap*, const char*, struct ns1__ProbeType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ByeType
#define SOAP_TYPE_PointerTons1__ByeType (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ByeType(struct soap*, struct ns1__ByeType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ByeType(struct soap*, struct ns1__ByeType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ByeType(struct soap*, const char *, int, struct ns1__ByeType *const*, const char *);
SOAP_FMAC3 struct ns1__ByeType ** SOAP_FMAC4 soap_get_PointerTons1__ByeType(struct soap*, struct ns1__ByeType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ByeType ** SOAP_FMAC4 soap_in_PointerTons1__ByeType(struct soap*, const char*, struct ns1__ByeType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ResolveType
#define SOAP_TYPE_PointerTons1__ResolveType (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ResolveType(struct soap*, struct ns1__ResolveType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ResolveType(struct soap*, struct ns1__ResolveType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ResolveType(struct soap*, const char *, int, struct ns1__ResolveType *const*, const char *);
SOAP_FMAC3 struct ns1__ResolveType ** SOAP_FMAC4 soap_get_PointerTons1__ResolveType(struct soap*, struct ns1__ResolveType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ResolveType ** SOAP_FMAC4 soap_in_PointerTons1__ResolveType(struct soap*, const char*, struct ns1__ResolveType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__HelloType
#define SOAP_TYPE_PointerTons1__HelloType (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__HelloType(struct soap*, struct ns1__HelloType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__HelloType(struct soap*, struct ns1__HelloType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__HelloType(struct soap*, const char *, int, struct ns1__HelloType *const*, const char *);
SOAP_FMAC3 struct ns1__HelloType ** SOAP_FMAC4 soap_get_PointerTons1__HelloType(struct soap*, struct ns1__HelloType **, const char*, const char*);
SOAP_FMAC3 struct ns1__HelloType ** SOAP_FMAC4 soap_in_PointerTons1__HelloType(struct soap*, const char*, struct ns1__HelloType **, const char*);

#ifndef SOAP_TYPE_PointerTons2__ServiceNameType
#define SOAP_TYPE_PointerTons2__ServiceNameType (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ServiceNameType(struct soap*, struct ns2__ServiceNameType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ServiceNameType(struct soap*, struct ns2__ServiceNameType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ServiceNameType(struct soap*, const char *, int, struct ns2__ServiceNameType *const*, const char *);
SOAP_FMAC3 struct ns2__ServiceNameType ** SOAP_FMAC4 soap_get_PointerTons2__ServiceNameType(struct soap*, struct ns2__ServiceNameType **, const char*, const char*);
SOAP_FMAC3 struct ns2__ServiceNameType ** SOAP_FMAC4 soap_in_PointerTons2__ServiceNameType(struct soap*, const char*, struct ns2__ServiceNameType **, const char*);

#ifndef SOAP_TYPE_PointerTons2__AttributedQName
#define SOAP_TYPE_PointerTons2__AttributedQName (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__AttributedQName(struct soap*, struct ns2__AttributedQName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__AttributedQName(struct soap*, struct ns2__AttributedQName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__AttributedQName(struct soap*, const char *, int, struct ns2__AttributedQName *const*, const char *);
SOAP_FMAC3 struct ns2__AttributedQName ** SOAP_FMAC4 soap_get_PointerTons2__AttributedQName(struct soap*, struct ns2__AttributedQName **, const char*, const char*);
SOAP_FMAC3 struct ns2__AttributedQName ** SOAP_FMAC4 soap_in_PointerTons2__AttributedQName(struct soap*, const char*, struct ns2__AttributedQName **, const char*);

#ifndef SOAP_TYPE_PointerTons2__ReferenceParametersType
#define SOAP_TYPE_PointerTons2__ReferenceParametersType (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ReferenceParametersType(struct soap*, struct ns2__ReferenceParametersType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ReferenceParametersType(struct soap*, struct ns2__ReferenceParametersType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ReferenceParametersType(struct soap*, const char *, int, struct ns2__ReferenceParametersType *const*, const char *);
SOAP_FMAC3 struct ns2__ReferenceParametersType ** SOAP_FMAC4 soap_get_PointerTons2__ReferenceParametersType(struct soap*, struct ns2__ReferenceParametersType **, const char*, const char*);
SOAP_FMAC3 struct ns2__ReferenceParametersType ** SOAP_FMAC4 soap_in_PointerTons2__ReferenceParametersType(struct soap*, const char*, struct ns2__ReferenceParametersType **, const char*);

#ifndef SOAP_TYPE_PointerTons2__ReferencePropertiesType
#define SOAP_TYPE_PointerTons2__ReferencePropertiesType (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ReferencePropertiesType(struct soap*, struct ns2__ReferencePropertiesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ReferencePropertiesType(struct soap*, struct ns2__ReferencePropertiesType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ReferencePropertiesType(struct soap*, const char *, int, struct ns2__ReferencePropertiesType *const*, const char *);
SOAP_FMAC3 struct ns2__ReferencePropertiesType ** SOAP_FMAC4 soap_get_PointerTons2__ReferencePropertiesType(struct soap*, struct ns2__ReferencePropertiesType **, const char*, const char*);
SOAP_FMAC3 struct ns2__ReferencePropertiesType ** SOAP_FMAC4 soap_in_PointerTons2__ReferencePropertiesType(struct soap*, const char*, struct ns2__ReferencePropertiesType **, const char*);

#ifndef SOAP_TYPE_PointerTons2__AttributedURI
#define SOAP_TYPE_PointerTons2__AttributedURI (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__AttributedURI(struct soap*, struct ns2__AttributedURI *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__AttributedURI(struct soap*, struct ns2__AttributedURI *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__AttributedURI(struct soap*, const char *, int, struct ns2__AttributedURI *const*, const char *);
SOAP_FMAC3 struct ns2__AttributedURI ** SOAP_FMAC4 soap_get_PointerTons2__AttributedURI(struct soap*, struct ns2__AttributedURI **, const char*, const char*);
SOAP_FMAC3 struct ns2__AttributedURI ** SOAP_FMAC4 soap_in_PointerTons2__AttributedURI(struct soap*, const char*, struct ns2__AttributedURI **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, struct xsd__base64Binary *const*, const char *);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary **, const char*);

#ifndef SOAP_TYPE_PointerTons1__SigType
#define SOAP_TYPE_PointerTons1__SigType (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SigType(struct soap*, struct ns1__SigType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SigType(struct soap*, struct ns1__SigType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SigType(struct soap*, const char *, int, struct ns1__SigType *const*, const char *);
SOAP_FMAC3 struct ns1__SigType ** SOAP_FMAC4 soap_get_PointerTons1__SigType(struct soap*, struct ns1__SigType **, const char*, const char*);
SOAP_FMAC3 struct ns1__SigType ** SOAP_FMAC4 soap_in_PointerTons1__SigType(struct soap*, const char*, struct ns1__SigType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ResolveMatchType
#define SOAP_TYPE_PointerTons1__ResolveMatchType (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ResolveMatchType(struct soap*, struct ns1__ResolveMatchType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ResolveMatchType(struct soap*, struct ns1__ResolveMatchType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ResolveMatchType(struct soap*, const char *, int, struct ns1__ResolveMatchType *const*, const char *);
SOAP_FMAC3 struct ns1__ResolveMatchType ** SOAP_FMAC4 soap_get_PointerTons1__ResolveMatchType(struct soap*, struct ns1__ResolveMatchType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ResolveMatchType ** SOAP_FMAC4 soap_in_PointerTons1__ResolveMatchType(struct soap*, const char*, struct ns1__ResolveMatchType **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ProbeMatchType
#define SOAP_TYPE_PointerTons1__ProbeMatchType (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProbeMatchType(struct soap*, struct ns1__ProbeMatchType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProbeMatchType(struct soap*, struct ns1__ProbeMatchType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProbeMatchType(struct soap*, const char *, int, struct ns1__ProbeMatchType *const*, const char *);
SOAP_FMAC3 struct ns1__ProbeMatchType ** SOAP_FMAC4 soap_get_PointerTons1__ProbeMatchType(struct soap*, struct ns1__ProbeMatchType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ProbeMatchType ** SOAP_FMAC4 soap_in_PointerTons1__ProbeMatchType(struct soap*, const char*, struct ns1__ProbeMatchType **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedInt(struct soap*, unsigned int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedInt(struct soap*, unsigned int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedInt(struct soap*, const char *, int, unsigned int *const*, const char *);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_get_PointerTounsignedInt(struct soap*, unsigned int **, const char*, const char*);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_in_PointerTounsignedInt(struct soap*, const char*, unsigned int **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ScopesType
#define SOAP_TYPE_PointerTons1__ScopesType (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ScopesType(struct soap*, struct ns1__ScopesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ScopesType(struct soap*, struct ns1__ScopesType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ScopesType(struct soap*, const char *, int, struct ns1__ScopesType *const*, const char *);
SOAP_FMAC3 struct ns1__ScopesType ** SOAP_FMAC4 soap_get_PointerTons1__ScopesType(struct soap*, struct ns1__ScopesType **, const char*, const char*);
SOAP_FMAC3 struct ns1__ScopesType ** SOAP_FMAC4 soap_in_PointerTons1__ScopesType(struct soap*, const char*, struct ns1__ScopesType **, const char*);

#ifndef SOAP_TYPE_PointerTons2__EndpointReferenceType
#define SOAP_TYPE_PointerTons2__EndpointReferenceType (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__EndpointReferenceType(struct soap*, struct ns2__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__EndpointReferenceType(struct soap*, struct ns2__EndpointReferenceType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__EndpointReferenceType(struct soap*, const char *, int, struct ns2__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct ns2__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTons2__EndpointReferenceType(struct soap*, struct ns2__EndpointReferenceType **, const char*, const char*);
SOAP_FMAC3 struct ns2__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTons2__EndpointReferenceType(struct soap*, const char*, struct ns2__EndpointReferenceType **, const char*);

#ifndef SOAP_TYPE_ns1__FaultCodeOpenType
#define SOAP_TYPE_ns1__FaultCodeOpenType (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__FaultCodeOpenType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__FaultCodeOpenType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__FaultCodeOpenType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__FaultCodeOpenType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns1__FaultCodeOpenType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns1__FaultCodeOpenType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_ns1__UriListType
#define SOAP_TYPE_ns1__UriListType (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__UriListType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__UriListType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__UriListType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__UriListType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns1__UriListType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns1__UriListType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_ns1__QNameListType
#define SOAP_TYPE_ns1__QNameListType (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__QNameListType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__QNameListType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__QNameListType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__QNameListType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns1__QNameListType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns1__QNameListType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_ns1__OpenRelationshipType
#define SOAP_TYPE_ns1__OpenRelationshipType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__OpenRelationshipType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__OpenRelationshipType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__OpenRelationshipType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__OpenRelationshipType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns1__OpenRelationshipType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns1__OpenRelationshipType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__nonNegativeInteger(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__nonNegativeInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__nonNegativeInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__nonNegativeInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__NCName
#define SOAP_TYPE_xsd__NCName (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__NCName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__NCName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__NCName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__NCName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__NCName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__NCName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__IDREFS
#define SOAP_TYPE_xsd__IDREFS (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__IDREFS(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__IDREFS(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__IDREFS(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__IDREFS(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__IDREFS(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__IDREFS(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__ID
#define SOAP_TYPE_xsd__ID (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__ID(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__ID(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__ID(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ID(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__ID(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__ID(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
