/* soapClient.c
   Generated by gSOAP 2.7.9l from onvif.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9l 2015-07-30 02:05:25 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__HelloType *tdn__Hello, struct ns1__ResolveType *tdn__HelloResponse)
{	struct __ns3__Hello soap_tmp___ns3__Hello;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver10/network/wsdl/Hello";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__Hello.tdn__Hello = tdn__Hello;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__Hello(soap, &soap_tmp___ns3__Hello);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__Hello(soap, &soap_tmp___ns3__Hello, "-ns3:Hello", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__Hello(soap, &soap_tmp___ns3__Hello, "-ns3:Hello", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns1__ResolveType(soap, tdn__HelloResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ResolveType(soap, tdn__HelloResponse, "tdn:HelloResponse", "ns1:ResolveType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__ByeType *tdn__Bye, struct ns1__ResolveType *tdn__ByeResponse)
{	struct __ns3__Bye soap_tmp___ns3__Bye;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver10/network/wsdl/Bye";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__Bye.tdn__Bye = tdn__Bye;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__Bye(soap, &soap_tmp___ns3__Bye);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__Bye(soap, &soap_tmp___ns3__Bye, "-ns3:Bye", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__Bye(soap, &soap_tmp___ns3__Bye, "-ns3:Bye", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns1__ResolveType(soap, tdn__ByeResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ResolveType(soap, tdn__ByeResponse, "tdn:ByeResponse", "ns1:ResolveType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__ProbeType *tdn__Probe, struct ns1__ProbeMatchesType *tdn__ProbeResponse)
{	struct __ns4__Probe soap_tmp___ns4__Probe;
	if (!soap_action)
		soap_action = "http://www.onvif.org/ver10/network/wsdl/Probe";
	soap->encodingStyle = NULL;
	soap_tmp___ns4__Probe.tdn__Probe = tdn__Probe;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns4__Probe(soap, &soap_tmp___ns4__Probe);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns4__Probe(soap, &soap_tmp___ns4__Probe, "-ns4:Probe", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns4__Probe(soap, &soap_tmp___ns4__Probe, "-ns4:Probe", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns1__ProbeMatchesType(soap, tdn__ProbeResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ProbeMatchesType(soap, tdn__ProbeResponse, "tdn:ProbeResponse", "ns1:ProbeMatchesType");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
